/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SingleWomenNamibiaRouteImport } from './routes/single-women-namibia'
import { Route as SingleMenNamibiaRouteImport } from './routes/single-men-namibia'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as DatingInNamibiaRouteImport } from './routes/dating-in-namibia'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedLikesRouteImport } from './routes/_authenticated/likes'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfileIdRouteImport } from './routes/_authenticated/profile.$id'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleWomenNamibiaRoute = SingleWomenNamibiaRouteImport.update({
  id: '/single-women-namibia',
  path: '/single-women-namibia',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleMenNamibiaRoute = SingleMenNamibiaRouteImport.update({
  id: '/single-men-namibia',
  path: '/single-men-namibia',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DatingInNamibiaRoute = DatingInNamibiaRouteImport.update({
  id: '/dating-in-namibia',
  path: '/dating-in-namibia',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLikesRoute = AuthenticatedLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIdRoute = AuthenticatedProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMessagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/dating-in-namibia': typeof DatingInNamibiaRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/single-men-namibia': typeof SingleMenNamibiaRoute
  '/single-women-namibia': typeof SingleWomenNamibiaRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/likes': typeof AuthenticatedLikesRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/dating-in-namibia': typeof DatingInNamibiaRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/single-men-namibia': typeof SingleMenNamibiaRoute
  '/single-women-namibia': typeof SingleWomenNamibiaRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/likes': typeof AuthenticatedLikesRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/dating-in-namibia': typeof DatingInNamibiaRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/single-men-namibia': typeof SingleMenNamibiaRoute
  '/single-women-namibia': typeof SingleWomenNamibiaRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/likes': typeof AuthenticatedLikesRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/profile/$id': typeof AuthenticatedProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/dating-in-namibia'
    | '/plans'
    | '/privacy'
    | '/safety'
    | '/single-men-namibia'
    | '/single-women-namibia'
    | '/terms'
    | '/admin'
    | '/browse'
    | '/likes'
    | '/me'
    | '/messages'
    | '/onboarding'
    | '/messages/$id'
    | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/dating-in-namibia'
    | '/plans'
    | '/privacy'
    | '/safety'
    | '/single-men-namibia'
    | '/single-women-namibia'
    | '/terms'
    | '/admin'
    | '/browse'
    | '/likes'
    | '/me'
    | '/messages'
    | '/onboarding'
    | '/messages/$id'
    | '/profile/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/community-guidelines'
    | '/dating-in-namibia'
    | '/plans'
    | '/privacy'
    | '/safety'
    | '/single-men-namibia'
    | '/single-women-namibia'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/browse'
    | '/_authenticated/likes'
    | '/_authenticated/me'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/messages/$id'
    | '/_authenticated/profile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  DatingInNamibiaRoute: typeof DatingInNamibiaRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SingleMenNamibiaRoute: typeof SingleMenNamibiaRoute
  SingleWomenNamibiaRoute: typeof SingleWomenNamibiaRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-women-namibia': {
      id: '/single-women-namibia'
      path: '/single-women-namibia'
      fullPath: '/single-women-namibia'
      preLoaderRoute: typeof SingleWomenNamibiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-men-namibia': {
      id: '/single-men-namibia'
      path: '/single-men-namibia'
      fullPath: '/single-men-namibia'
      preLoaderRoute: typeof SingleMenNamibiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dating-in-namibia': {
      id: '/dating-in-namibia'
      path: '/dating-in-namibia'
      fullPath: '/dating-in-namibia'
      preLoaderRoute: typeof DatingInNamibiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/likes': {
      id: '/_authenticated/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof AuthenticatedLikesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/$id': {
      id: '/_authenticated/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AuthenticatedProfileIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
  }
}

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedLikesRoute: typeof AuthenticatedLikesRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileIdRoute: typeof AuthenticatedProfileIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedLikesRoute: AuthenticatedLikesRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileIdRoute: AuthenticatedProfileIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  DatingInNamibiaRoute: DatingInNamibiaRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SingleMenNamibiaRoute: SingleMenNamibiaRoute,
  SingleWomenNamibiaRoute: SingleWomenNamibiaRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
